/**
 * Mock of @tauri-apps/api/core.
 *
 * The copied bindings.ts (generated by tauri-specta) routes every command
 * through `invoke(cmd, args)`. Rather than rewrite bindings, we keep it
 * verbatim and make this single `invoke` the replacement backend: getters
 * return canned data from src/mock/state.ts, mutators are no-ops, and the
 * model "download" command drives the event bus (src/mock/bus.ts) the same way
 * the real Rust backend would.
 */
import { emit } from "./bus";
import { state, markModelDownloaded, removeModel, setCurrentModel } from "./state";

export class Channel<T = unknown> {
  callback: ((response: T) => void) | null = null;
  onmessage(cb: (response: T) => void) {
    this.callback = cb;
  }
  send(data: T) {
    this.callback?.(data);
  }
}

export function convertFileSrc(filePath: string): string {
  return filePath;
}

/** Simulate a model download: emit progress, verify, extract, complete. */
function simulateDownload(modelId: string): void {
  const model = state.models.find((m) => m.id === modelId);
  const total = Math.max(1, (model?.size_mb ?? 100) * 1024 * 1024);
  let downloaded = 0;

  const step = () => {
    downloaded += total / 12;
    const percentage = Math.min(100, Math.round((downloaded / total) * 100));
    emit("model-download-progress", {
      model_id: modelId,
      downloaded: Math.min(downloaded, total),
      total,
      percentage,
    });

    if (percentage < 100) {
      setTimeout(step, 220);
      return;
    }

    emit("model-verification-started", modelId);
    setTimeout(() => {
      emit("model-verification-completed", modelId);
      emit("model-extraction-started", modelId);
      setTimeout(() => {
        emit("model-extraction-completed", modelId);
        markModelDownloaded(modelId);
        emit("model-download-complete", modelId);
      }, 500);
    }, 500);
  };

  setTimeout(step, 150);
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function invoke(cmd: string, args: Record<string, any> = {}): Promise<any> {
  switch (cmd) {
    // --- Settings ---
    case "get_app_settings":
      return state.settings;
    case "get_default_settings":
      return state.defaultSettings;

    // --- Models ---
    case "get_available_models":
      return state.models.map((m) => ({
        ...m,
        is_downloaded: state.downloaded.has(m.id),
      }));
    case "get_model_info":
      return state.models.find((m) => m.id === args.modelId) ?? null;
    case "get_current_model":
      return state.currentModel;
    case "get_model_load_status":
      return {
        is_loaded: state.currentModel !== "",
        current_model: state.currentModel || null,
      };
    case "get_transcription_model_status":
      return null;
    case "is_model_loading":
      return false;
    case "has_any_models_available":
    case "has_any_models_or_downloads":
      return state.downloaded.size > 0;

    case "download_model":
      simulateDownload(args.modelId as string);
      return null;
    case "cancel_download":
      return null;
    case "delete_model":
      removeModel(args.modelId as string);
      return null;
    case "set_active_model":
      setCurrentModel(args.modelId as string);
      return null;
    case "unload_model_manually":
      return null;

    // --- Audio devices ---
    case "get_available_microphones":
      return state.microphones;
    case "get_available_output_devices":
      return state.outputDevices;
    case "get_microphone_mode":
      return state.settings.always_on_microphone ?? false;
    case "get_selected_microphone":
      return state.settings.selected_microphone ?? "default";
    case "get_selected_output_device":
      return state.settings.selected_output_device ?? "default";
    case "get_clamshell_microphone":
      return state.settings.clamshell_microphone ?? "default";
    case "check_custom_sounds":
      return { start: false, stop: false };

    // --- Platform / environment ---
    case "get_available_typing_tools":
      return ["auto", "wtype", "kwtype", "dotool", "ydotool", "xdotool"];
    case "get_keyboard_implementation":
      return state.settings.keyboard_implementation ?? "tauri";
    case "get_available_accelerators":
      return { whisper: ["auto", "cpu", "gpu"], ort: ["auto", "cpu"], gpu_devices: [] };
    case "is_portable":
      return false;
    case "is_laptop":
      return true;
    case "is_recording":
      return false;
    case "check_apple_intelligence_available":
      return false;

    // --- History ---
    case "get_history_entries":
      return { entries: state.history, has_more: false };
    case "get_audio_file_path":
      return "";

    // --- Paths ---
    case "get_app_dir_path":
      return "/Users/mock/aivision/data";
    case "get_log_dir_path":
      return "/Users/mock/aivision/logs";

    // --- Post-processing ---
    case "fetch_post_process_models":
      return [];

    // --- All change_/set_/update_/toggle_/open_/etc. mutators: no-op ---
    default:
      return null;
  }
}
